### ISSUE TITLE
Local Storage Saved after Refresh

### ISSUE THREAD

**Issue by ColinMudie** [JJG1488/group-project#27]
as it stands, refreshing the page will remove the saved searches. we should add another array to store the current local storage data on so that when we reset the page the saved data remains.

If we do this we should also add either a clear button or a way to remove an individual item off the list.

**Comment by JJG1488** [comment]
Created array that pushes users last input into the local storage. On page refresh, last search is shown on the previous search list and pulled from the local storage as the search value.
